### PR TITLE
Adding BlurryBar stuffs to BlurBar

### PR DESCRIPTION
**Pull request by PoomSmart**
- Using SBWallpaperEffectView instead of CKBlurView for blurring effect.
- New preferences pane added (for choosing blur style, DockShift method), while keeping the old one if you want to improve that existing instead.
- Using Flipswitch instead. (More easier to toggle the feature)
- New screenshot.
- Yes, you can consider choosing them for further development.

### CODE REVIEW

**Comment by insanj** [comment]
Thanks for the pull request! Unfortunately, it looks like all commits [but one](https://github.com/PoomSmart/BlurBar/commit/ca8cb2d28052c69eecf1025427328318620f5aeb) are entirely unrealted to the functioning and structure of BlurBar itself, and [destroy my handiwork](https://github.com/PoomSmart/BlurBar/commit/90435e5a0bfbdb9de93f934a7a1ac79f1ad3fa87) simply to allow BlurryBar to exist unchallenged. If you'd like me to merge this with the current branch, could you clean up the request a bit, and make it so only necessary changes are made? I'd love to combine these two tweaks, but this is clearly not a mutual partnership ;)

---

Note: if you want to replace Activator support with FlipSwitch support, and other such major changes, it would be best to split up the work into separate pull requests for each components. Cheers.

**Comment by PoomSmart** [comment]
So did you still want the new blur method?

**Comment by insanj** [comment]
It's up to you how to integrate our codebases together. I simply suggested we take steps to create a better, combination product that could have the best of each independant product. This pull request didn't quite fill that space in a reasonable way, as I outlined in the closing comment, where I also left instructions for how I'd prefer changes be made.

**Comment by PoomSmart** [comment]
I know that. After the final test, I will start doing this.

**Comment by insanj** [comment]
How's progress? I'd still love to combine and augment our products in a productive and beneficial way.

**Comment by PoomSmart** [comment]
I was busy or had no idea how I can combine these project together.

What about letting users choose those blur methods: CKBlurView, or SBWallpaperEffectView ?

**Comment by insanj** [comment]
It would be more suitable to simply continue with the progress you began and teased about before (["After the final test, I will start doing this"](https://github.com/insanj/BlurBar/pull/2#issuecomment-55217715)), with the alterations (in style, approach, and content) we dicussed. The only necessity I could think of would be [a toggle for the auto show / hide](https://github.com/insanj/BlurBar/issues/3), besides that, you can use the expectations I posted above:

> ...it looks like all commits but one are entirely unrelated to the functioning and structure of BlurBar itself... If you'd like me to merge this with the current branch, could you clean up the request a bit, and make it so only necessary changes are made?
> 
> ...if you want to replace Activator support with FlipSwitch support, and other such major changes, it would be best to split up the work into separate pull requests for each components.
> 
> ...[I suggest] we take steps to create a better, combination product that could have the best of each independant product.

Of course, if any techniques in BlurryBar are more efficient than BlurBar, such as the `SBWallpaperEffectView`, that'd be a very good augmentation to include in a pull request— I'm not sure why we'd offer the user the choice between either, though! I'm sure one has better performance.

**Pull request closed without merging**
